os: linux
dist: xenial
language: python
python:
  - '3.8'
cache: pip

before_install:
  - sudo rm -rf /var/lib/redis/*
  - wget https://github.com/antirez/redis/archive/6.0-rc3.tar.gz && tar xzf 6.0-rc3.tar.gz && cd redis-6.0-rc3 && make

install:
  - cd /home/travis/build/elcolumbio/fastcounting/
  - mv /home/travis/build/elcolumbio/fastcounting/fastcounting.yaml /home/travis/.config/fastcounting.yaml
  - pip install -r requirements.txt
  - pip install .

services: redis

script:
  - flake8 ./fastcounting/
  - flake8 ./tests
  - pytest